aws_smtp_relay:
  image:
    repository: <MY awesome repo>
    tag: latest
    pull_policy: Always
  AWS_REGION: "eu-west-1"
airflow:
  image:
    repository: airflow:latest
    tag: latest
  executor: Local
  service:
    type: NodePort
  config:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 30
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow #connection can be stored in kubernetes secrets
    AIRFLOW__CORE__FERNET_KEY: <YOUR-FERNET-KEY>
    AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS: true
    AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE: false
    # Don't load airflow dag from db
    AIRFLOW__CORE__STORE_DAG_CODE: false

    # logs
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    AIRFLOW__LOGGING__FAB_LOGGING_LEVEL: INFO

    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 120
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 30
    AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD: 240

    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: true
    AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE: true


    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: airflow:latest
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: latest
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: IfNotPresent
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: airflow-logs
    AIRFLOW__KUBERNETES__NAMESPACE: default
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: true


    POSTGRES_HOST: airflow-postgresql
    ENV: unknown

dags:
  path: /usr/local/airflow/dags

web:
  initialStartupDelay: "30"
  initialDelaySeconds: "30"

postgresql:
  enabled: true
  postgresqlUsername: <Read from secrets>
  postgresqlDatabase: <Read from secrets>
  postgresqlPassword: <Read from secrets>
  resources:
    requests:
      cpu: 50m

logsPersistence:
  accessMode: ReadWriteOnce
  size: 3Gi

## Create or use ServiceAccount
serviceAccount:
  create: false
  name: airflow