airflow:
  image:
    repository: airflow:latest
    tag: latest
  executor: Local
  service:
    type: NodePort
  config:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: true
    AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS: true
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: airflow:latest
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: latest
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: IfNotPresent
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: airflow-logs
    AIRFLOW__KUBERNETES__NAMESPACE: default
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: true
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: <YOUR-FERNET-KEY>
    POSTGRES_HOST: airflow-postgresql
    ENV: unknown

dags:
  path: /usr/local/airflow/dags

web:
  initialStartupDelay: "30"
  initialDelaySeconds: "30"

rbac:
  create: false

## Create or use ServiceAccount
serviceAccount:
  create: false
  name: airflow
