apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "airflow-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
     helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.logsPersistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.logsPersistence.size }}
